config/routes.rb
Rails.application.routes.draw do
  resources :user_profiles
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "user_profiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_one :user_profile, dependent: :destroy

  normalizes :email, with: ->(e) { e.strip.downcase }
  validates :email, presence: true, uniqueness: true

  after_create :create_profile

  private

  # This method creates a user profile after the user is created
  def create_profile
    create_user_profile(
      user: self            # Pass the entire user instance
    )
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user

  # Associations with Active Storage for profile image
  has_one_attached :profile_img do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  # Validations
  validates :first_name, length: { maximum: 100 }, allow_blank: true
  validates :last_name, length: { maximum: 100 }, allow_blank: true

  # Apply uniqueness and format validations only if phone_number is present
  validates :phone_number, uniqueness: true, if: :phone_number_present?
  validates :phone_number, format: { with: /\A[0-9\-\+\(\)\s]*\z/, message: "only allows valid phone numbers" }, if: :phone_number_present?

  private

  # Check if phone_number is present
  def phone_number_present?
    phone_number.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email: params[:email])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: %i[ show edit update destroy ]

  # GET /user_profiles or /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1 or /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles or /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: "User profile was successfully created." }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1 or /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: "User profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1 or /user_profiles/1.json
  def destroy
    @user_profile.destroy!

    respond_to do |format|
      format.html { redirect_to user_profiles_path, status: :see_other, notice: "User profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      params.expect(user_profile: [ :user_id, :first_name, :last_name, :phone_number, :email, :profile_img ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Inbody App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="relative pt-6 pb-12 bg-gray-300 dark:bg-slate-700" id="navbar">
  <div class="flex flex-row text-slate-800 dark:text-white">
    <%= link_to 'My InBody', root_path, class: "btn btn-ghost text-xl left-4 top-5 absolute text-slate-800 dark:text-white" %>
    <ul class="flex flex-row space-x-10 items-center justify-start px-1 inset-x-44 w-3/4 absolute" id="navigation">
      <li>
        <%= link_to 'All scans', root_path, id: "all_scans", class: current_page?(root_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
      </li>
    </ul>
  </div>
</nav>

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile, class: "contents") do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul class="list-disc ml-6">
        <% user_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_profile.errors[:user_id].none?, "border-red-400 focus:outline-red-600": user_profile.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_profile.errors[:first_name].none?, "border-red-400 focus:outline-red-600": user_profile.errors[:first_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_profile.errors[:last_name].none?, "border-red-400 focus:outline-red-600": user_profile.errors[:last_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_profile.errors[:phone_number].none?, "border-red-400 focus:outline-red-600": user_profile.errors[:phone_number].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :profile_img %>
    <%= form.file_field :profile_img, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_profile.errors[:profile_img].none?, "border-red-400 focus:outline-red-600": user_profile.errors[:profile_img].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_profiles/_user_profile.html.erb
<div id="<%= dom_id user_profile %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-3xl mb-1">User profile</strong>
  </div>
  <div>
    <strong class="block font-medium mb-1">First name:</strong>
    <%= user_profile.first_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= user_profile.last_name %>
  </div>
    <div>
    <strong class="block font-medium mb-1">Email:</strong>
    <%= User.find(user_profile.user_id).email %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Phone number:</strong>
    <%= user_profile.phone_number %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Profile img:</strong>

    <% if user_profile.profile_img.attached? %>
      <%= image_tag user_profile.profile_img.variant(:thumb) %>
    <% else %>
      <%= image_tag "default_profile.jpg", size: "100x100", alt: "Default Profile Image" %>
    <% end %>
    </div>

</div>

app/views/user_profiles/edit.html.erb
<% content_for :title, "Editing user profile" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user profile</h1>

  <%= render "form", user_profile: @user_profile %>

  <%= link_to "Show this user profile", @user_profile, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to user profiles", user_profiles_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/user_profiles/index.html.erb
<% content_for :title, "User profiles" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">User profiles</h1>
    <%= link_to "New user profile", new_user_profile_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="user_profiles" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @user_profiles.any? %>
      <% @user_profiles.each do |user_profile| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render user_profile %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", user_profile, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_user_profile_path(user_profile), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="sm:inline-block">
              <%= button_to "Destroy", user_profile, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No user profiles found.</p>
    <% end %>
  </div>
</div>

app/views/user_profiles/new.html.erb
<% content_for :title, "New user profile" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user profile</h1>

  <%= render "form", user_profile: @user_profile %>

  <%= link_to "Back to user profiles", user_profiles_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/user_profiles/show.html.erb
<% content_for :title, "Showing user profile" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing user profile</h1>

  <%= render @user_profile %>

  <%= link_to "Edit this user profile", edit_user_profile_path(@user_profile), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to user profiles", user_profiles_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this user profile", @user_profile, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>